import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
      <>
          <Head>
              <title>d-app example</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={styles.container}>
              <header className={styles.header}>
                  <img className={styles.logo} src='/eth-logo.svg'/>
                  <h2 className={styles.title}>d-app example</h2>
              </header>
              <p className={styles.paragraph}>Welkom op mijn d-app message app. Elk vierde bericht krijgt 1/10 Eth.</p>
                  <h2>Stuur een bericht</h2>
                  <form>
                      <div className={styles.formField}>
                          <label className={styles.label}>Op welk adres kunnen we de ethers storten ?</label>
                          <input className={styles.input} type='text'/>
                      </div>
                      <div className={styles.formField}>
                          <label className={styles.label}>Wat is je bericht ?</label>
                          <textarea className={styles.input} rows="4" cols="50"></textarea>
                          <input className={styles.button} type='submit' value='verstuur het nu'/>
                      </div>
                      <div className={styles.formField}>
                          <label className={styles.label}>Hoeveel geld wil je op het contract storten ?</label>
                          <input className={styles.input} type='text'/>
                          <input className={styles.button} type='submit' value='Stort geld op dit contract'/>
                      </div>
                      <div className={styles.formField}>
                          <label className={styles.label}>Welk berichtnummer wil je ophalen ?</label>
                          <input className={styles.input} type='text'/>
                          <input className={styles.button} type='submit' value='Haal het op'/>
                      </div>
                  </form>
          </div>
      </>
  )
}

export default Home
